#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=: read -r username password user_id group_id user_id_inf home_dir command; do
	echo "The user ${username} is part of the ${group_id} gang, lives in ${home_dir} and rides ${command}. ${user_id}'s place is protected by the passcode ${password}, more info about the user here: ${user_id_inf}"
done < /etc/passwd
