#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
c=1
while [ $c -le 10 ]
do
	if [ $c = 9  ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	c=$((c+1))
done
