#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 20 and prints different messages using case

c=1
while [ $c -le 20 ]
do
    case $c in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo "Best School"
            ;;
    esac

    c=$((c + 1))
done
