#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes
h=0
m=1
while [ $h -le 12 ]
do
echo "Hour: $h"
while [ $m -le 59 ]
do
	echo $m
	m=$((m+1))
done
m=1
h=$((h+1))
done
