#!/usr/bin/env bash
# Write a Bash script that gives information about school file

if [ -f "school" ]
then
    echo "school is a regular file"
fi

if [ -e "school" ]
then
    echo "school file exists"
fi

if [ ! -s "school" ]
then
    echo "school file is empty"
fi
